# Create video from numpy array and images


# Video from numpy array

In [1]:
import numpy as np
import cv2
import os

In [2]:
height = 1280
width = 720
channel = 3
frame_per_sec = 30
sec = 5    # 20 sec
print("Video height-> ",height)
print("Video width-> ",width)
print("Video channel(RGB color)-> ",channel)
print("frame_per_sec-> ",frame_per_sec)
print("Video second-> ",sec)

Video height->  1280
Video width->  720
Video channel(RGB color)->  3
frame_per_sec->  30
Video second->  5


In [3]:
fourcc = cv2.VideoWriter_fourcc(*'MP42')
videos = cv2.VideoWriter('videos/demo.mkv', fourcc, float(frame_per_sec), (width,height))
print("Object->",videos)

Object-> <VideoWriter 0x7f829a527950>


In [4]:
for frame_count in range(frame_per_sec*sec):
    img = np.random.randint(0,255, (height, width, channel), dtype = np.uint8)
    print("Image Matrix -> ",img)
    videos.write(img)
 
videos.release()

Image Matrix ->  [[[ 87  34 118]
  [136 105  91]
  [ 49  54 192]
  ...
  [200 163 253]
  [ 25  18  55]
  [198 134 120]]

 [[114 189 229]
  [213 174 214]
  [210  43 127]
  ...
  [ 12  19 173]
  [ 12 106 178]
  [ 95   0 106]]

 [[ 52 204 112]
  [224  93 129]
  [164  79  24]
  ...
  [216 175  79]
  [225 223  32]
  [171 164 232]]

 ...

 [[160 113  62]
  [233 129 198]
  [ 97 205  60]
  ...
  [237  93   4]
  [ 57  34 128]
  [172  49  96]]

 [[231 199  87]
  [202 252 107]
  [189 104 159]
  ...
  [ 97  10 217]
  [146 197  22]
  [ 68 190 117]]

 [[228 212  98]
  [  1 110  84]
  [  3 202 149]
  ...
  [216  69 164]
  [ 26 145 217]
  [214 204  22]]]
Image Matrix ->  [[[ 80 246  95]
  [241 187  92]
  [ 22 202  67]
  ...
  [ 49 137 116]
  [203 118 152]
  [119   7 202]]

 [[ 86  17 180]
  [ 68 235  94]
  [126 124  23]
  ...
  [186 128 175]
  [195 156 120]
  [ 52  21 146]]

 [[ 79 109 200]
  [ 54 198  51]
  [167  30  23]
  ...
  [118 254 144]
  [115 218  40]
  [160  56 162]]

 ...

 [[ 83 201 121]
  

Image Matrix ->  [[[ 27 211 211]
  [228 203   9]
  [ 36 130  19]
  ...
  [ 76 107   1]
  [ 67  53  32]
  [ 50  74  43]]

 [[138  59 239]
  [172 222 196]
  [239 223  53]
  ...
  [ 22 230 169]
  [ 17 251 228]
  [249 100  12]]

 [[245 110  70]
  [179  18  39]
  [161 118 211]
  ...
  [  8 133 124]
  [  2  41 236]
  [ 77 242 209]]

 ...

 [[117 103   5]
  [ 53 242 249]
  [178 217 160]
  ...
  [172 216 217]
  [183  65 123]
  [112  35  60]]

 [[104 154 163]
  [  4 193 100]
  [  9 187 216]
  ...
  [187 154  55]
  [197   1 191]
  [ 91 108 196]]

 [[ 51 228 174]
  [ 34 100  68]
  [ 45 176  20]
  ...
  [202 197  85]
  [164  12 152]
  [193 223 156]]]
Image Matrix ->  [[[127  93 236]
  [160 190 185]
  [217  29  64]
  ...
  [ 92  92  29]
  [ 95 224 118]
  [233 106 216]]

 [[ 93  11 206]
  [248 145 252]
  [ 24 112  41]
  ...
  [243  79 163]
  [224 174 144]
  [125  51  15]]

 [[182 110  14]
  [ 36 125 133]
  [ 47  32 241]
  ...
  [148 187 228]
  [  7 121  29]
  [ 75  98  68]]

 ...

 [[ 91  87 162]
  

Image Matrix ->  [[[120 208 164]
  [ 45 171  67]
  [ 10   4 130]
  ...
  [148  12 163]
  [204   9 169]
  [254 208  81]]

 [[  6  69 102]
  [ 79  55 185]
  [ 31   2 180]
  ...
  [ 61  52  94]
  [116 252  97]
  [153 100 207]]

 [[183 116 142]
  [188 177 208]
  [208 227 212]
  ...
  [199 227 163]
  [221 117   3]
  [ 44 130 154]]

 ...

 [[236 134 251]
  [173 197  82]
  [177  42 184]
  ...
  [ 49  13 208]
  [191 233  20]
  [107 100  58]]

 [[ 52  14 223]
  [213  62  24]
  [ 96  37  80]
  ...
  [147  25  99]
  [ 85  47 142]
  [213 124 157]]

 [[ 51  15 158]
  [199  95  88]
  [ 53 227   7]
  ...
  [141 102  75]
  [ 16 205 102]
  [103 220  61]]]
Image Matrix ->  [[[ 10  39 133]
  [ 41  61  36]
  [200  25  97]
  ...
  [ 58 123  31]
  [182 251  24]
  [161 113 106]]

 [[143 131  36]
  [254 160 219]
  [146  28   8]
  ...
  [134  42  20]
  [177 143 233]
  [209  72   6]]

 [[222 245  68]
  [218 162 236]
  [215  36 191]
  ...
  [ 51  93  71]
  [135  75 143]
  [ 77 183 221]]

 ...

 [[123 237 183]
  

Image Matrix ->  [[[ 30  39 153]
  [ 61  12 138]
  [ 48 247  29]
  ...
  [  7 246  75]
  [209 231  86]
  [155 158  70]]

 [[130 186 166]
  [169 241 118]
  [  4 150 231]
  ...
  [ 71 179 156]
  [224 234 125]
  [ 30 122 164]]

 [[241 205 164]
  [195 125 154]
  [210 196 252]
  ...
  [ 83  17 251]
  [ 53 207  61]
  [ 12  40  85]]

 ...

 [[183 205 147]
  [133 225  96]
  [186 181 227]
  ...
  [ 70 122 142]
  [127  63 165]
  [ 27 101 143]]

 [[158  78  39]
  [135 186  60]
  [ 14  98 216]
  ...
  [125   0 133]
  [155  70  86]
  [193  36  28]]

 [[205  89 227]
  [158   6  90]
  [ 47 154 238]
  ...
  [ 17 120  91]
  [ 77 168 208]
  [188 164  83]]]
Image Matrix ->  [[[215 113  62]
  [136 233   7]
  [ 76 128 106]
  ...
  [140 226  74]
  [232 190 178]
  [239  98 164]]

 [[ 85 120 125]
  [133  91 220]
  [ 34 136 136]
  ...
  [211 230 250]
  [ 26 221 253]
  [110 114  92]]

 [[127  12 163]
  [137 238  14]
  [220 124  20]
  ...
  [233  66  32]
  [  3 229 172]
  [ 26 141  55]]

 ...

 [[ 87 160 101]
  

Image Matrix ->  [[[ 19  80  62]
  [183 203 190]
  [ 54 162  39]
  ...
  [ 17  45 134]
  [125  72  23]
  [198  73  50]]

 [[181 238 136]
  [ 11  49  56]
  [185 103 242]
  ...
  [ 81 151   6]
  [167  18 229]
  [ 11 162   8]]

 [[168 147 158]
  [240 213  92]
  [250  54  45]
  ...
  [ 37 212  60]
  [ 55 245  25]
  [165 206 179]]

 ...

 [[227  50 160]
  [246 196  98]
  [185  82 218]
  ...
  [ 53 118 227]
  [179  86   5]
  [195   1  12]]

 [[154 121  93]
  [ 36  51 234]
  [156 163 145]
  ...
  [ 45  62 246]
  [ 15 134  95]
  [163  48 118]]

 [[200  80 213]
  [213  21 216]
  [173 138 115]
  ...
  [ 56  85 223]
  [175 199 248]
  [138 185 187]]]
Image Matrix ->  [[[158 180 142]
  [194 235  69]
  [231 209  99]
  ...
  [219 217 167]
  [ 76  98 139]
  [ 84  24 103]]

 [[189 252  23]
  [ 42 216 118]
  [185  91 168]
  ...
  [195  65   0]
  [ 92   8 237]
  [ 11  71 164]]

 [[ 23 161  51]
  [225 208 107]
  [233 114 154]
  ...
  [ 12  80 236]
  [ 61  44 205]
  [217 111 216]]

 ...

 [[149   7  49]
  

Image Matrix ->  [[[ 84  62 164]
  [  2  26 129]
  [ 58 106  42]
  ...
  [132 238 238]
  [106 220 185]
  [139 161 203]]

 [[122 132 249]
  [243  48 221]
  [101 102 253]
  ...
  [219  72   0]
  [215 142   9]
  [106 242 210]]

 [[176 153 142]
  [ 49 226 224]
  [177  79 242]
  ...
  [135 130  69]
  [200 114 113]
  [124  34  13]]

 ...

 [[ 58 160 228]
  [ 12  85 236]
  [187 102  72]
  ...
  [ 15  35 199]
  [188 237 126]
  [210  11  32]]

 [[132 151  11]
  [215 148  74]
  [  2  54 196]
  ...
  [  7 161 177]
  [110 164 177]
  [237 115 190]]

 [[110  98 204]
  [ 14 175  81]
  [233  17 242]
  ...
  [ 29 116  16]
  [118 162 111]
  [ 13  20 208]]]
Image Matrix ->  [[[ 22 238 143]
  [233  72  29]
  [131 147  25]
  ...
  [ 46  68 183]
  [136 141  47]
  [ 91 159  78]]

 [[115 183 144]
  [234 136 224]
  [201  31  91]
  ...
  [151 225  54]
  [ 19 222  10]
  [222 159 103]]

 [[222 118  55]
  [  2 204 127]
  [229 217  15]
  ...
  [ 89  19  45]
  [123 240 224]
  [ 64  38 121]]

 ...

 [[ 92  59  70]
  

Image Matrix ->  [[[ 60 118 132]
  [ 30  23 225]
  [ 16 103 164]
  ...
  [ 22 129 184]
  [241 120   4]
  [214 142  65]]

 [[201  56 183]
  [ 72 218 240]
  [194 229 193]
  ...
  [ 96 230 163]
  [194  29  56]
  [248   5 194]]

 [[ 12 183 109]
  [125 186  20]
  [249  71 111]
  ...
  [131  19  20]
  [ 54 215 148]
  [ 24  60  61]]

 ...

 [[124   6 108]
  [154  94   3]
  [147 176 163]
  ...
  [170 167 245]
  [209 124 148]
  [247 191 193]]

 [[125 158  54]
  [100  87  44]
  [105 197 190]
  ...
  [  2  55  10]
  [219  88 181]
  [213  88  42]]

 [[ 88  13  65]
  [204 239 232]
  [ 31  86  75]
  ...
  [146 132  59]
  [101 240 188]
  [192  62 182]]]
Image Matrix ->  [[[170  71 211]
  [241 232 239]
  [227 168  65]
  ...
  [ 74  87 118]
  [ 98   7  93]
  [ 56 173 190]]

 [[ 15  17   3]
  [ 88   9 184]
  [ 69 235 226]
  ...
  [101 186 228]
  [ 13  36 176]
  [207  53  26]]

 [[ 84 166  18]
  [ 62  66 144]
  [239 117  83]
  ...
  [225 142 254]
  [ 64 125 152]
  [ 73 116 215]]

 ...

 [[188 170  13]
  

Image Matrix ->  [[[193 209 179]
  [148  22 234]
  [229 153 228]
  ...
  [162 232 117]
  [248  94  36]
  [152 125  34]]

 [[156 108 119]
  [ 30 146  60]
  [ 54 174 158]
  ...
  [134 153 241]
  [210 247 244]
  [ 80 157 214]]

 [[229  93  37]
  [112 117   5]
  [176   0  76]
  ...
  [ 64 180 228]
  [ 76 242 218]
  [ 31 206 184]]

 ...

 [[234  77   7]
  [ 32  57 105]
  [ 72  35  98]
  ...
  [217 115 207]
  [234  28  72]
  [189  59  76]]

 [[234 154 125]
  [243  96  42]
  [ 24  54  58]
  ...
  [211  95  74]
  [170 127 166]
  [216 189  55]]

 [[112 248 236]
  [  2  98 112]
  [240   9 200]
  ...
  [184 196 217]
  [ 43 103 174]
  [187 182 223]]]
Image Matrix ->  [[[119 109 100]
  [220 112  87]
  [163  51 126]
  ...
  [ 93 151  12]
  [210  46  55]
  [192  33 126]]

 [[144 248  81]
  [242 240 139]
  [ 66 211  94]
  ...
  [143 214 211]
  [103 132 238]
  [226  26  25]]

 [[ 36 250  33]
  [137 175  68]
  [124  51 205]
  ...
  [232 125 166]
  [ 84  76 106]
  [178 203 189]]

 ...

 [[ 70 113  35]
  

Image Matrix ->  [[[109  76 144]
  [170 237 147]
  [123   8  99]
  ...
  [  6  66  84]
  [157  73 186]
  [253  99  54]]

 [[174  62   2]
  [176  68 218]
  [ 84  39  69]
  ...
  [ 84  93 148]
  [124  20 113]
  [168  56 148]]

 [[143 182   9]
  [165 117 230]
  [125 208 121]
  ...
  [  3 234 101]
  [250 184  29]
  [ 23  27  14]]

 ...

 [[213 222 174]
  [173  86  23]
  [ 61 208  33]
  ...
  [ 81 184 102]
  [133 199  88]
  [243  89  27]]

 [[236 124  92]
  [192 145 199]
  [210 210  94]
  ...
  [101   5  59]
  [171 202   0]
  [196 226   6]]

 [[237  89  46]
  [166 176  86]
  [ 83 140 216]
  ...
  [ 41 226  67]
  [115 110 199]
  [185  62 226]]]
Image Matrix ->  [[[159 237 175]
  [ 27 196  35]
  [254  33 244]
  ...
  [154 104 103]
  [195 104 247]
  [105  53 201]]

 [[ 39 155  11]
  [ 45 139 167]
  [142 147  78]
  ...
  [251 161 134]
  [175 132 240]
  [246 243 208]]

 [[ 78   3 239]
  [ 27 184  74]
  [ 27 220  34]
  ...
  [146  56 158]
  [ 57 197 241]
  [ 36  47  72]]

 ...

 [[169 226  19]
  

Image Matrix ->  [[[ 50 134 224]
  [166 245 171]
  [  3 147 179]
  ...
  [230 163 158]
  [  7  84  62]
  [  2 189 227]]

 [[ 95  85 123]
  [101  54 158]
  [203 252 192]
  ...
  [229 127  52]
  [116  63  16]
  [ 93 131  25]]

 [[100 188 114]
  [231  71 122]
  [ 27 232  40]
  ...
  [ 42 172   5]
  [ 66 116  20]
  [ 83  59 149]]

 ...

 [[ 34 108 209]
  [113   7 132]
  [210 199 108]
  ...
  [168 218  29]
  [ 21 221 111]
  [190 204  21]]

 [[240  27  34]
  [161  23 178]
  [178 241 234]
  ...
  [110 250 123]
  [228 162  49]
  [ 35 121 251]]

 [[200  72 119]
  [238  25 214]
  [ 93  55 175]
  ...
  [179 100  87]
  [152 217 238]
  [144  26  62]]]
Image Matrix ->  [[[218 181 133]
  [192  73 125]
  [ 48 185 157]
  ...
  [ 58  47  35]
  [145 244   2]
  [226  76 163]]

 [[ 83  83 223]
  [  8 164   3]
  [165  17 235]
  ...
  [ 21 145 114]
  [ 56   6 135]
  [ 15   2  38]]

 [[ 62  96 135]
  [208   9  48]
  [178 195  91]
  ...
  [123 189 206]
  [ 35 101 171]
  [221  19 166]]

 ...

 [[ 30 106 106]
  

Image Matrix ->  [[[111 160 118]
  [236 213  30]
  [155  46  85]
  ...
  [ 17 214 102]
  [ 90 120 118]
  [ 10 172 147]]

 [[ 51 158  21]
  [168  62 220]
  [180  15   1]
  ...
  [216  32  88]
  [122 239 254]
  [ 43 147 142]]

 [[172 182  20]
  [237 223 130]
  [177 196 188]
  ...
  [157 189 205]
  [124  60  68]
  [105  35 138]]

 ...

 [[156 160 222]
  [192  94 137]
  [ 39 220 129]
  ...
  [ 65  94   6]
  [160  24 100]
  [ 88 215 209]]

 [[ 69  13 179]
  [226   2  67]
  [ 56 188 236]
  ...
  [209  89  64]
  [ 71 228 194]
  [ 25 248   2]]

 [[106  55  75]
  [ 72 190 229]
  [ 15 137  94]
  ...
  [ 52 162 110]
  [154  13 248]
  [ 16 101 111]]]
Image Matrix ->  [[[ 11 182  98]
  [193 132 160]
  [ 77 174 105]
  ...
  [242 238  54]
  [223 125  25]
  [182 143  38]]

 [[164  83 199]
  [248  88   8]
  [231 200  16]
  ...
  [200 133  74]
  [  5 223 162]
  [240 105   5]]

 [[ 93 232  10]
  [ 95 252 242]
  [230 248  37]
  ...
  [160 210 143]
  [169 140 190]
  [237  35 135]]

 ...

 [[ 76 245 152]
  

# Video from images


In [5]:
height = 1280
width = 720
channel = 3
frame_per_sec = 10
sec = 20    # 5 sec

print("Video height-> ",height)
print("Video width-> ",width)
print("Video channel(RGB color)-> ",channel)
print("frame_per_sec-> ",frame_per_sec)
print("Video second-> ",sec)

Video height->  1280
Video width->  720
Video channel(RGB color)->  3
frame_per_sec->  10
Video second->  20


In [6]:
four_cc = cv2.VideoWriter_fourcc(*'MP42')
video_img = cv2.VideoWriter('videos/demo_images.mkv', four_cc, float(frame_per_sec), (width,height))
print("Object->",video_img)

Object-> <VideoWriter 0x7f829a527b30>


In [7]:
path = 'new_created_directory'
image_list = os.listdir(path)
print(image_list)

['created_image136.png', 'created_image214.png', 'created_image33.png', 'created_image183.png', 'created_image94.png', 'created_image11.png', 'created_image161.png', 'created_image157.png', 'created_image9.png', 'created_image174.png', 'created_image32.png', 'created_image298.png', 'created_image78.png', 'created_image83.png', 'created_image271.png', 'created_image21.png', 'created_image365.png', 'created_image250.png', 'created_image338.png', 'created_image193.png', 'created_image368.png', 'created_image167.png', 'created_image409.png', 'created_image75.png', 'created_image187.png', 'created_image306.png', 'created_image90.png', 'created_image96.png', 'created_image236.png', 'created_image16.png', 'created_image34.png', 'created_image44.png', 'created_image407.png', 'created_image343.png', 'created_image48.png', 'created_image382.png', 'created_image177.png', 'created_image17.png', 'created_image111.png', 'created_image375.png', 'created_image279.png', 'created_image254.png', 'created

In [8]:
for frame in range(frame_per_sec*sec):
    # select images randomly
    image_name = np.random.choice(image_list)
    print("Ranodmly Select image name -> ",image_name)
    # here join path + image
    img_path = os.path.join(path + '/' +image_name)
    print("Image full path -> ",img_path)
    # read image
    images = cv2.imread(img_path)
    print(images)
    image_resize = cv2.resize(images, (width,height))
    
    video_img.write(image_resize)
    
video_img.release()

Ranodmly Select image name ->  created_image301.png
Image full path ->  new_created_directory/created_image301.png
[[[100  83  57]
  [ 97  80  54]
  [ 91  74  48]
  ...
  [ 90  69  48]
  [ 90  69  48]
  [ 90  69  48]]

 [[100  83  57]
  [ 97  80  54]
  [ 91  74  48]
  ...
  [ 90  69  48]
  [ 90  69  48]
  [ 90  69  48]]

 [[100  83  57]
  [ 97  80  54]
  [ 91  74  48]
  ...
  [ 90  69  48]
  [ 90  69  48]
  [ 90  69  48]]

 ...

 [[142 148 152]
  [142 148 152]
  [142 148 152]
  ...
  [136 146 163]
  [137 147 164]
  [137 147 164]]

 [[142 148 152]
  [142 148 152]
  [142 148 152]
  ...
  [136 146 163]
  [136 146 163]
  [137 147 164]]

 [[142 148 152]
  [142 148 152]
  [142 148 152]
  ...
  [136 146 163]
  [136 146 163]
  [136 146 163]]]
Result None
Ranodmly Select image name ->  created_image279.png
Image full path ->  new_created_directory/created_image279.png
[[[134 156 146]
  [120 142 132]
  [ 91 106  95]
  ...
  [ 71  77  58]
  [ 85  97  75]
  [ 93 105  83]]

 [[136 158 148]
  [122 1

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Result None
Ranodmly Select image name ->  created_image33.png
Image full path ->  new_created_directory/created_image33.png
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Result None
Ranodmly Select image name ->  crea

[[[106 101  86]
  [106 101  86]
  [106 101  86]
  ...
  [115 109  97]
  [115 109  97]
  [115 109  97]]

 [[106 101  86]
  [106 101  86]
  [106 101  86]
  ...
  [115 109  97]
  [115 109  97]
  [115 109  97]]

 [[106 101  86]
  [106 101  86]
  [106 101  86]
  ...
  [115 109  97]
  [115 109  97]
  [115 109  97]]

 ...

 [[105 108  83]
  [105 108  83]
  [105 108  83]
  ...
  [104 114  92]
  [104 113  94]
  [104 113  94]]

 [[105 108  83]
  [105 108  83]
  [105 108  83]
  ...
  [104 112  95]
  [104 111  97]
  [104 111  97]]

 [[105 108  83]
  [105 108  83]
  [105 108  83]
  ...
  [104 112  95]
  [104 111  97]
  [104 111  97]]]
Result None
Ranodmly Select image name ->  created_image404.png
Image full path ->  new_created_directory/created_image404.png
[[[246 230 167]
  [246 230 167]
  [246 230 167]
  ...
  [ 21  13   8]
  [ 20  12   7]
  [ 20  12   7]]

 [[246 230 167]
  [246 230 167]
  [246 230 167]
  ...
  [ 21  13   8]
  [ 20  12   7]
  [ 20  12   7]]

 [[246 230 167]
  [246 230 167]
  [

[[[214 197 157]
  [189 172 132]
  [142 125  85]
  ...
  [ 73  59  39]
  [ 58  44  24]
  [ 47  33  13]]

 [[214 197 157]
  [189 172 132]
  [142 125  85]
  ...
  [ 73  59  39]
  [ 58  44  24]
  [ 47  33  13]]

 [[214 197 157]
  [189 172 132]
  [142 125  85]
  ...
  [ 73  59  39]
  [ 58  44  24]
  [ 47  33  13]]

 ...

 [[148 156 187]
  [148 156 187]
  [148 156 187]
  ...
  [133 134 152]
  [133 134 152]
  [132 133 151]]

 [[150 158 189]
  [150 158 189]
  [150 158 189]
  ...
  [132 133 151]
  [131 132 150]
  [131 132 150]]

 [[150 158 189]
  [150 158 189]
  [150 158 189]
  ...
  [131 132 150]
  [130 131 149]
  [130 131 149]]]
Result None
Ranodmly Select image name ->  created_image238.png
Image full path ->  new_created_directory/created_image238.png
[[[122 144 125]
  [122 144 125]
  [121 143 124]
  ...
  [129 150 134]
  [128 152 135]
  [129 153 136]]

 [[122 144 125]
  [122 144 125]
  [121 143 124]
  ...
  [129 150 134]
  [128 152 135]
  [128 152 135]]

 [[122 144 125]
  [122 144 125]
  [

Result None
Ranodmly Select image name ->  created_image392.png
Image full path ->  new_created_directory/created_image392.png
[[[117 147 125]
  [117 147 125]
  [117 147 125]
  ...
  [ 21  13  13]
  [ 21  13  13]
  [ 21  13  13]]

 [[117 147 125]
  [117 147 125]
  [117 147 125]
  ...
  [ 21  13  13]
  [ 21  13  13]
  [ 21  13  13]]

 [[117 147 125]
  [117 147 125]
  [117 147 125]
  ...
  [ 21  13  13]
  [ 21  13  13]
  [ 21  13  13]]

 ...

 [[152 160 203]
  [150 158 201]
  [146 154 197]
  ...
  [137 140 158]
  [138 141 159]
  [138 141 159]]

 [[149 157 200]
  [146 154 197]
  [142 150 193]
  ...
  [136 139 157]
  [137 140 158]
  [137 140 158]]

 [[149 157 200]
  [146 154 197]
  [140 148 191]
  ...
  [135 138 156]
  [136 139 157]
  [136 139 157]]]
Result None
Ranodmly Select image name ->  created_image224.png
Image full path ->  new_created_directory/created_image224.png
[[[190 172 135]
  [190 172 135]
  [190 172 135]
  ...
  [204 197 169]
  [204 197 169]
  [204 197 169]]

 [[190 172 1

Ranodmly Select image name ->  created_image116.png
Image full path ->  new_created_directory/created_image116.png
[[[194 184 157]
  [194 184 157]
  [194 184 157]
  ...
  [208 199 178]
  [208 199 178]
  [208 199 178]]

 [[194 184 157]
  [194 184 157]
  [194 184 157]
  ...
  [208 199 178]
  [208 199 178]
  [208 199 178]]

 [[194 184 157]
  [194 184 157]
  [194 184 157]
  ...
  [208 199 178]
  [208 199 178]
  [208 199 178]]

 ...

 [[187 197 152]
  [191 201 156]
  [189 200 158]
  ...
  [175 203 162]
  [179 204 164]
  [182 207 167]]

 [[187 197 152]
  [189 199 154]
  [185 196 154]
  ...
  [159 186 148]
  [171 196 156]
  [179 204 164]]

 [[187 197 152]
  [187 197 152]
  [181 192 150]
  ...
  [140 167 129]
  [167 192 152]
  [181 206 166]]]
Result None
Ranodmly Select image name ->  created_image145.png
Image full path ->  new_created_directory/created_image145.png
[[[195 182 152]
  [195 182 152]
  [195 182 152]
  ...
  [209 197 175]
  [209 197 175]
  [209 197 175]]

 [[195 182 152]
  [195 1

[[[122 144 125]
  [122 144 125]
  [122 144 125]
  ...
  [125 149 132]
  [125 149 132]
  [126 150 133]]

 [[121 143 124]
  [121 143 124]
  [121 143 124]
  ...
  [126 150 133]
  [126 150 133]
  [126 150 133]]

 [[121 143 124]
  [121 143 124]
  [121 143 124]
  ...
  [126 150 133]
  [126 150 133]
  [126 150 133]]

 ...

 [[ 70  86  73]
  [ 69  85  72]
  [ 68  84  71]
  ...
  [ 65  83  71]
  [ 65  83  71]
  [ 65  83  71]]

 [[ 68  84  71]
  [ 67  83  70]
  [ 65  81  68]
  ...
  [ 63  81  69]
  [ 63  81  69]
  [ 63  81  69]]

 [[ 67  83  70]
  [ 65  81  68]
  [ 64  80  67]
  ...
  [ 63  81  69]
  [ 63  81  69]
  [ 63  81  69]]]
Result None
Ranodmly Select image name ->  created_image86.png
Image full path ->  new_created_directory/created_image86.png
[[[106 101  86]
  [106 101  86]
  [106 101  86]
  ...
  [115 109  97]
  [115 109  97]
  [115 109  97]]

 [[106 101  86]
  [106 101  86]
  [106 101  86]
  ...
  [115 109  97]
  [115 109  97]
  [115 109  97]]

 [[106 101  86]
  [106 101  86]
  [10

[[[82 78 68]
  [82 78 68]
  [82 78 68]
  ...
  [88 83 75]
  [88 83 75]
  [88 83 75]]

 [[82 78 68]
  [82 78 68]
  [82 78 68]
  ...
  [88 83 75]
  [88 83 75]
  [88 83 75]]

 [[81 77 67]
  [81 77 67]
  [81 77 67]
  ...
  [88 83 75]
  [88 83 75]
  [88 83 75]]

 ...

 [[81 82 71]
  [81 82 71]
  [83 84 71]
  ...
  [80 88 71]
  [80 88 71]
  [79 87 70]]

 [[80 81 68]
  [82 83 70]
  [81 83 67]
  ...
  [80 88 71]
  [80 88 71]
  [80 88 71]]

 [[81 82 69]
  [81 82 69]
  [80 82 66]
  ...
  [80 88 71]
  [80 88 71]
  [80 88 71]]]
Result None
Ranodmly Select image name ->  created_image389.png
Image full path ->  new_created_directory/created_image389.png
[[[212 220 180]
  [222 230 190]
  [242 245 220]
  ...
  [ 73  80  86]
  [ 73  80  86]
  [ 73  80  86]]

 [[215 223 183]
  [226 234 194]
  [246 249 224]
  ...
  [ 72  79  85]
  [ 72  79  85]
  [ 72  79  85]]

 [[222 228 195]
  [232 238 205]
  [253 255 234]
  ...
  [ 71  78  84]
  [ 71  78  84]
  [ 71  78  84]]

 ...

 [[138 146 189]
  [138 146 189]
 

Result None
Ranodmly Select image name ->  created_image313.png
Image full path ->  new_created_directory/created_image313.png
[[[253 229 170]
  [253 229 170]
  [253 229 170]
  ...
  [ 18  16  12]
  [ 18  16  12]
  [ 18  16  12]]

 [[253 229 170]
  [253 229 170]
  [253 229 170]
  ...
  [ 18  16  12]
  [ 18  16  12]
  [ 18  16  12]]

 [[253 229 170]
  [253 229 170]
  [253 229 170]
  ...
  [ 18  16  12]
  [ 18  16  12]
  [ 18  16  12]]

 ...

 [[140 149 150]
  [141 150 151]
  [141 150 151]
  ...
  [133 143 153]
  [133 143 153]
  [133 143 153]]

 [[141 150 151]
  [142 151 152]
  [141 150 151]
  ...
  [133 143 153]
  [133 143 153]
  [133 143 153]]

 [[141 150 151]
  [142 151 152]
  [141 150 151]
  ...
  [132 142 152]
  [132 142 152]
  [132 142 152]]]
Result None
Ranodmly Select image name ->  created_image199.png
Image full path ->  new_created_directory/created_image199.png
[[[198 175 134]
  [198 175 134]
  [198 175 134]
  ...
  [217 199 170]
  [217 199 170]
  [217 199 170]]

 [[198 175 1

Result None
Ranodmly Select image name ->  created_image120.png
Image full path ->  new_created_directory/created_image120.png
[[[194 182 155]
  [194 182 155]
  [194 182 155]
  ...
  [208 199 176]
  [208 199 176]
  [208 199 176]]

 [[194 182 155]
  [194 182 155]
  [194 182 155]
  ...
  [208 199 176]
  [208 199 176]
  [208 199 176]]

 [[196 184 157]
  [196 184 157]
  [196 184 157]
  ...
  [208 199 176]
  [208 199 176]
  [208 199 176]]

 ...

 [[150 168 136]
  [139 157 125]
  [122 145 117]
  ...
  [ 88 120  86]
  [102 129  96]
  [122 149 116]]

 [[120 143 115]
  [110 133 105]
  [111 137 115]
  ...
  [ 90 124  90]
  [ 95 127  93]
  [ 82 114  80]]

 [[115 138 110]
  [111 134 106]
  [116 142 120]
  ...
  [ 98 132  98]
  [ 98 130  96]
  [ 77 109  75]]]
Result None
Ranodmly Select image name ->  created_image361.png
Image full path ->  new_created_directory/created_image361.png
[[[253 229 170]
  [253 229 170]
  [253 229 170]
  ...
  [ 20  17  11]
  [ 20  17  11]
  [ 20  17  11]]

 [[253 229 1

Result None
Ranodmly Select image name ->  created_image167.png
Image full path ->  new_created_directory/created_image167.png
[[[197 181 147]
  [197 181 147]
  [197 181 147]
  ...
  [213 198 173]
  [213 198 173]
  [213 198 173]]

 [[197 181 147]
  [197 181 147]
  [197 181 147]
  ...
  [213 198 173]
  [213 198 173]
  [213 198 173]]

 [[197 181 147]
  [197 181 147]
  [197 181 147]
  ...
  [213 198 173]
  [213 198 173]
  [213 198 173]]

 ...

 [[102 160 130]
  [104 162 132]
  [113 166 137]
  ...
  [113 163 137]
  [111 162 138]
  [111 162 138]]

 [[102 160 130]
  [104 162 132]
  [113 166 137]
  ...
  [112 162 136]
  [110 161 137]
  [110 161 137]]

 [[102 160 130]
  [104 162 132]
  [113 166 137]
  ...
  [110 160 134]
  [108 159 135]
  [108 159 135]]]
Result None
Ranodmly Select image name ->  created_image139.png
Image full path ->  new_created_directory/created_image139.png
[[[196 183 153]
  [196 183 153]
  [196 183 153]
  ...
  [209 197 175]
  [209 197 175]
  [209 197 175]]

 [[196 183 1

Ranodmly Select image name ->  created_image258.png
Image full path ->  new_created_directory/created_image258.png
[[[125 144 128]
  [122 141 125]
  [119 138 122]
  ...
  [137 158 144]
  [137 158 144]
  [137 158 144]]

 [[125 144 128]
  [123 142 126]
  [120 139 123]
  ...
  [137 158 144]
  [135 156 142]
  [134 155 141]]

 [[122 141 125]
  [122 141 125]
  [118 137 121]
  ...
  [129 150 136]
  [125 146 132]
  [125 146 132]]

 ...

 [[121 125 127]
  [121 125 127]
  [121 125 127]
  ...
  [111 112 107]
  [111 112 107]
  [111 112 107]]

 [[121 125 127]
  [121 125 127]
  [121 125 127]
  ...
  [111 112 107]
  [111 112 107]
  [111 112 107]]

 [[121 125 127]
  [121 125 127]
  [121 125 127]
  ...
  [110 111 106]
  [110 111 106]
  [110 111 106]]]
Result None
Ranodmly Select image name ->  created_image350.png
Image full path ->  new_created_directory/created_image350.png
[[[112  90  39]
  [112  90  39]
  [112  90  39]
  ...
  [107 105 101]
  [119 117 113]
  [128 126 122]]

 [[112  90  39]
  [112  

[[[199 175 136]
  [199 175 136]
  [199 175 136]
  ...
  [216 198 169]
  [216 198 169]
  [216 198 169]]

 [[199 175 136]
  [199 175 136]
  [199 175 136]
  ...
  [216 198 169]
  [216 198 169]
  [216 198 169]]

 [[199 175 136]
  [199 175 136]
  [199 175 136]
  ...
  [216 198 169]
  [216 198 169]
  [216 198 169]]

 ...

 [[132 161 155]
  [132 161 155]
  [132 161 155]
  ...
  [109 128 114]
  [109 128 114]
  [109 128 114]]

 [[132 161 155]
  [132 161 155]
  [132 161 155]
  ...
  [109 128 114]
  [109 128 114]
  [109 128 114]]

 [[132 161 155]
  [132 161 155]
  [132 161 155]
  ...
  [109 128 114]
  [109 128 114]
  [109 128 114]]]
Result None
Ranodmly Select image name ->  created_image272.png
Image full path ->  new_created_directory/created_image272.png
[[[134 158 148]
  [132 156 146]
  [128 154 144]
  ...
  [102 113  89]
  [102 114  92]
  [102 114  92]]

 [[134 158 148]
  [131 155 145]
  [125 151 141]
  ...
  [101 112  88]
  [102 114  92]
  [103 115  93]]

 [[134 158 148]
  [131 155 145]
  [

[[[201 174 131]
  [201 174 131]
  [201 174 131]
  ...
  [218 198 168]
  [218 198 168]
  [218 198 168]]

 [[201 174 131]
  [201 174 131]
  [201 174 131]
  ...
  [218 198 168]
  [218 198 168]
  [218 198 168]]

 [[201 174 131]
  [201 174 131]
  [201 174 131]
  ...
  [218 198 168]
  [218 198 168]
  [218 198 168]]

 ...

 [[101 120 104]
  [103 122 106]
  [104 123 107]
  ...
  [113 132 118]
  [110 129 115]
  [105 124 110]]

 [[101 120 104]
  [103 122 106]
  [104 123 107]
  ...
  [112 131 117]
  [109 128 114]
  [104 123 109]]

 [[101 120 104]
  [103 122 106]
  [104 123 107]
  ...
  [112 131 117]
  [109 128 114]
  [104 123 109]]]
Result None
Ranodmly Select image name ->  created_image283.png
Image full path ->  new_created_directory/created_image283.png
[[[62 68 58]
  [65 71 61]
  [59 62 52]
  ...
  [59 53 43]
  [56 50 40]
  [61 55 45]]

 [[43 49 39]
  [50 56 46]
  [52 55 45]
  ...
  [55 49 39]
  [48 42 32]
  [53 47 37]]

 [[32 40 30]
  [32 40 30]
  [38 44 34]
  ...
  [48 47 36]
  [36 37 26]


Result None
Ranodmly Select image name ->  created_image218.png
Image full path ->  new_created_directory/created_image218.png
[[[201 174 131]
  [201 174 131]
  [201 174 131]
  ...
  [218 198 168]
  [218 198 168]
  [218 198 168]]

 [[201 174 131]
  [201 174 131]
  [201 174 131]
  ...
  [218 198 168]
  [218 198 168]
  [218 198 168]]

 [[201 174 131]
  [201 174 131]
  [201 174 131]
  ...
  [218 198 168]
  [218 198 168]
  [218 198 168]]

 ...

 [[103 117 102]
  [103 117 102]
  [103 117 102]
  ...
  [108 126 114]
  [108 126 114]
  [108 126 114]]

 [[106 120 105]
  [106 120 105]
  [106 120 105]
  ...
  [106 124 112]
  [106 124 112]
  [106 124 112]]

 [[107 121 106]
  [107 121 106]
  [107 121 106]
  ...
  [105 123 111]
  [105 123 111]
  [105 123 111]]]
Result None
Ranodmly Select image name ->  created_image89.png
Image full path ->  new_created_directory/created_image89.png
[[[121 112  96]
  [121 112  96]
  [121 112  96]
  ...
  [126 120 108]
  [126 120 108]
  [126 120 108]]

 [[121 112  96

Result None
Ranodmly Select image name ->  created_image342.png
Image full path ->  new_created_directory/created_image342.png
[[[246 227 174]
  [246 227 174]
  [246 227 174]
  ...
  [ 20  19   8]
  [ 20  19   8]
  [ 20  19   8]]

 [[246 227 174]
  [246 227 174]
  [246 227 174]
  ...
  [ 20  19   8]
  [ 20  19   8]
  [ 20  19   8]]

 [[246 227 174]
  [246 227 174]
  [246 227 174]
  ...
  [ 20  19   8]
  [ 20  19   8]
  [ 20  19   8]]

 ...

 [[149 158 191]
  [149 158 191]
  [149 158 191]
  ...
  [128 122  96]
  [128 122  96]
  [128 122  96]]

 [[148 157 190]
  [148 157 190]
  [149 158 191]
  ...
  [128 122  96]
  [128 122  96]
  [128 122  96]]

 [[148 157 190]
  [148 157 190]
  [149 158 191]
  ...
  [129 123  97]
  [129 123  97]
  [129 123  97]]]
Result None
Ranodmly Select image name ->  created_image200.png
Image full path ->  new_created_directory/created_image200.png
[[[198 175 134]
  [198 175 134]
  [198 175 134]
  ...
  [217 199 170]
  [217 199 170]
  [217 199 170]]

 [[198 175 1

[[[194 184 157]
  [194 184 157]
  [194 184 157]
  ...
  [208 199 178]
  [208 199 178]
  [208 199 178]]

 [[194 184 157]
  [194 184 157]
  [194 184 157]
  ...
  [208 199 178]
  [208 199 178]
  [208 199 178]]

 [[194 184 157]
  [194 184 157]
  [194 184 157]
  ...
  [208 199 178]
  [208 199 178]
  [208 199 178]]

 ...

 [[189 202 155]
  [189 202 155]
  [187 201 151]
  ...
  [186 210 161]
  [186 211 157]
  [186 211 157]]

 [[187 200 153]
  [188 201 154]
  [187 201 151]
  ...
  [185 208 161]
  [185 210 158]
  [185 210 158]]

 [[187 200 153]
  [188 201 154]
  [187 201 151]
  ...
  [185 208 161]
  [185 210 158]
  [185 210 158]]]
Result None
